<?php

namespace AppBundle\Repository;

/**
 * OfferSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
