<?php

namespace AppBundle\Repository;

/**
 * UserOfferBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOfferBookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
